# Develop override settings

url                      : https://stefan-endres.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#url                      : http://localhost:4000   # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
